/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LoanBookV1Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveLiquidation"
      | "closeAgreement"
      | "createAgreement"
      | "emergencySafe"
      | "executeLiquidation"
      | "fundAgreement"
      | "getAgreement"
      | "lockCollateral"
      | "markDefaulted"
      | "owner"
      | "pause"
      | "paused"
      | "recordRepayment"
      | "releaseCollateral"
      | "renounceOwnership"
      | "setEmergencySafe"
      | "setTreasurySafe"
      | "startGracePeriod"
      | "startLiquidationReview"
      | "transferOwnership"
      | "treasurySafe"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgreementClosed"
      | "AgreementCreated"
      | "AgreementDefaulted"
      | "AgreementFunded"
      | "CollateralLocked"
      | "CollateralReleased"
      | "EmergencyPause"
      | "EmergencyResume"
      | "EmergencySafeUpdated"
      | "GracePeriodStarted"
      | "LiquidationApproved"
      | "LiquidationExecuted"
      | "LiquidationReviewStarted"
      | "OwnershipTransferred"
      | "Paused"
      | "RepaymentRecorded"
      | "TreasurySafeUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveLiquidation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "closeAgreement",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createAgreement",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencySafe",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeLiquidation",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundAgreement",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgreement",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockCollateral",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markDefaulted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordRepayment",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseCollateral",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setEmergencySafe",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasurySafe",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startGracePeriod",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startLiquidationReview",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "treasurySafe",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "approveLiquidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencySafe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeLiquidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markDefaulted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordRepayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEmergencySafe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasurySafe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startGracePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startLiquidationReview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasurySafe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace AgreementClosedEvent {
  export type InputTuple = [agreementId: BytesLike];
  export type OutputTuple = [agreementId: string];
  export interface OutputObject {
    agreementId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgreementCreatedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    borrower: AddressLike,
    treasuryReceiver: AddressLike,
    principalAmount: BigNumberish,
    collateralAmount: BigNumberish,
    serviceFeeAmount: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: string,
    borrower: string,
    treasuryReceiver: string,
    principalAmount: bigint,
    collateralAmount: bigint,
    serviceFeeAmount: bigint
  ];
  export interface OutputObject {
    agreementId: string;
    borrower: string;
    treasuryReceiver: string;
    principalAmount: bigint;
    collateralAmount: bigint;
    serviceFeeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgreementDefaultedEvent {
  export type InputTuple = [agreementId: BytesLike];
  export type OutputTuple = [agreementId: string];
  export interface OutputObject {
    agreementId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgreementFundedEvent {
  export type InputTuple = [agreementId: BytesLike, firstDueAt: BigNumberish];
  export type OutputTuple = [agreementId: string, firstDueAt: bigint];
  export interface OutputObject {
    agreementId: string;
    firstDueAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollateralLockedEvent {
  export type InputTuple = [agreementId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [agreementId: string, amount: bigint];
  export interface OutputObject {
    agreementId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollateralReleasedEvent {
  export type InputTuple = [agreementId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [agreementId: string, amount: bigint];
  export interface OutputObject {
    agreementId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyPauseEvent {
  export type InputTuple = [triggeredBy: AddressLike];
  export type OutputTuple = [triggeredBy: string];
  export interface OutputObject {
    triggeredBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyResumeEvent {
  export type InputTuple = [triggeredBy: AddressLike];
  export type OutputTuple = [triggeredBy: string];
  export interface OutputObject {
    triggeredBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencySafeUpdatedEvent {
  export type InputTuple = [
    previousEmergencySafe: AddressLike,
    nextEmergencySafe: AddressLike
  ];
  export type OutputTuple = [
    previousEmergencySafe: string,
    nextEmergencySafe: string
  ];
  export interface OutputObject {
    previousEmergencySafe: string;
    nextEmergencySafe: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GracePeriodStartedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    gracePeriodEndsAt: BigNumberish
  ];
  export type OutputTuple = [agreementId: string, gracePeriodEndsAt: bigint];
  export interface OutputObject {
    agreementId: string;
    gracePeriodEndsAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidationApprovedEvent {
  export type InputTuple = [agreementId: BytesLike];
  export type OutputTuple = [agreementId: string];
  export interface OutputObject {
    agreementId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidationExecutedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    recoveredAmount: BigNumberish,
    shortfallAmount: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: string,
    recoveredAmount: bigint,
    shortfallAmount: bigint
  ];
  export interface OutputObject {
    agreementId: string;
    recoveredAmount: bigint;
    shortfallAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidationReviewStartedEvent {
  export type InputTuple = [agreementId: BytesLike];
  export type OutputTuple = [agreementId: string];
  export interface OutputObject {
    agreementId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RepaymentRecordedEvent {
  export type InputTuple = [agreementId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [agreementId: string, amount: bigint];
  export interface OutputObject {
    agreementId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasurySafeUpdatedEvent {
  export type InputTuple = [
    previousTreasurySafe: AddressLike,
    nextTreasurySafe: AddressLike
  ];
  export type OutputTuple = [
    previousTreasurySafe: string,
    nextTreasurySafe: string
  ];
  export interface OutputObject {
    previousTreasurySafe: string;
    nextTreasurySafe: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LoanBookV1 extends BaseContract {
  connect(runner?: ContractRunner | null): LoanBookV1;
  waitForDeployment(): Promise<this>;

  interface: LoanBookV1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveLiquidation: TypedContractMethod<
    [agreementId: BytesLike],
    [void],
    "nonpayable"
  >;

  closeAgreement: TypedContractMethod<
    [agreementId: BytesLike],
    [void],
    "nonpayable"
  >;

  createAgreement: TypedContractMethod<
    [
      agreementId: BytesLike,
      borrower: AddressLike,
      borrowAsset: AddressLike,
      collateralAsset: AddressLike,
      treasuryReceiver: AddressLike,
      principalAmount: BigNumberish,
      collateralAmount: BigNumberish,
      serviceFeeAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  emergencySafe: TypedContractMethod<[], [string], "view">;

  executeLiquidation: TypedContractMethod<
    [
      agreementId: BytesLike,
      recoveredAmount: BigNumberish,
      shortfallAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  fundAgreement: TypedContractMethod<
    [agreementId: BytesLike, firstDueAt: BigNumberish],
    [void],
    "payable"
  >;

  getAgreement: TypedContractMethod<
    [agreementId: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        borrower: string;
        borrowAsset: string;
        collateralAsset: string;
        treasuryReceiver: string;
        principalAmount: bigint;
        collateralAmount: bigint;
        serviceFeeAmount: bigint;
        recoveredAmount: bigint;
        shortfallAmount: bigint;
        nextDueAt: bigint;
        state: bigint;
        collateralLocked: boolean;
        initialized: boolean;
      }
    ],
    "view"
  >;

  lockCollateral: TypedContractMethod<
    [agreementId: BytesLike, amount: BigNumberish],
    [void],
    "payable"
  >;

  markDefaulted: TypedContractMethod<
    [agreementId: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  recordRepayment: TypedContractMethod<
    [agreementId: BytesLike, amount: BigNumberish],
    [void],
    "payable"
  >;

  releaseCollateral: TypedContractMethod<
    [agreementId: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setEmergencySafe: TypedContractMethod<
    [nextEmergencySafe: AddressLike],
    [void],
    "nonpayable"
  >;

  setTreasurySafe: TypedContractMethod<
    [nextTreasurySafe: AddressLike],
    [void],
    "nonpayable"
  >;

  startGracePeriod: TypedContractMethod<
    [agreementId: BytesLike, gracePeriodEndsAt: BigNumberish],
    [void],
    "nonpayable"
  >;

  startLiquidationReview: TypedContractMethod<
    [agreementId: BytesLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasurySafe: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveLiquidation"
  ): TypedContractMethod<[agreementId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "closeAgreement"
  ): TypedContractMethod<[agreementId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createAgreement"
  ): TypedContractMethod<
    [
      agreementId: BytesLike,
      borrower: AddressLike,
      borrowAsset: AddressLike,
      collateralAsset: AddressLike,
      treasuryReceiver: AddressLike,
      principalAmount: BigNumberish,
      collateralAmount: BigNumberish,
      serviceFeeAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencySafe"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "executeLiquidation"
  ): TypedContractMethod<
    [
      agreementId: BytesLike,
      recoveredAmount: BigNumberish,
      shortfallAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundAgreement"
  ): TypedContractMethod<
    [agreementId: BytesLike, firstDueAt: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getAgreement"
  ): TypedContractMethod<
    [agreementId: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        borrower: string;
        borrowAsset: string;
        collateralAsset: string;
        treasuryReceiver: string;
        principalAmount: bigint;
        collateralAmount: bigint;
        serviceFeeAmount: bigint;
        recoveredAmount: bigint;
        shortfallAmount: bigint;
        nextDueAt: bigint;
        state: bigint;
        collateralLocked: boolean;
        initialized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockCollateral"
  ): TypedContractMethod<
    [agreementId: BytesLike, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "markDefaulted"
  ): TypedContractMethod<[agreementId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "recordRepayment"
  ): TypedContractMethod<
    [agreementId: BytesLike, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "releaseCollateral"
  ): TypedContractMethod<[agreementId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEmergencySafe"
  ): TypedContractMethod<
    [nextEmergencySafe: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasurySafe"
  ): TypedContractMethod<[nextTreasurySafe: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startGracePeriod"
  ): TypedContractMethod<
    [agreementId: BytesLike, gracePeriodEndsAt: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startLiquidationReview"
  ): TypedContractMethod<[agreementId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasurySafe"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AgreementClosed"
  ): TypedContractEvent<
    AgreementClosedEvent.InputTuple,
    AgreementClosedEvent.OutputTuple,
    AgreementClosedEvent.OutputObject
  >;
  getEvent(
    key: "AgreementCreated"
  ): TypedContractEvent<
    AgreementCreatedEvent.InputTuple,
    AgreementCreatedEvent.OutputTuple,
    AgreementCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AgreementDefaulted"
  ): TypedContractEvent<
    AgreementDefaultedEvent.InputTuple,
    AgreementDefaultedEvent.OutputTuple,
    AgreementDefaultedEvent.OutputObject
  >;
  getEvent(
    key: "AgreementFunded"
  ): TypedContractEvent<
    AgreementFundedEvent.InputTuple,
    AgreementFundedEvent.OutputTuple,
    AgreementFundedEvent.OutputObject
  >;
  getEvent(
    key: "CollateralLocked"
  ): TypedContractEvent<
    CollateralLockedEvent.InputTuple,
    CollateralLockedEvent.OutputTuple,
    CollateralLockedEvent.OutputObject
  >;
  getEvent(
    key: "CollateralReleased"
  ): TypedContractEvent<
    CollateralReleasedEvent.InputTuple,
    CollateralReleasedEvent.OutputTuple,
    CollateralReleasedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyPause"
  ): TypedContractEvent<
    EmergencyPauseEvent.InputTuple,
    EmergencyPauseEvent.OutputTuple,
    EmergencyPauseEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyResume"
  ): TypedContractEvent<
    EmergencyResumeEvent.InputTuple,
    EmergencyResumeEvent.OutputTuple,
    EmergencyResumeEvent.OutputObject
  >;
  getEvent(
    key: "EmergencySafeUpdated"
  ): TypedContractEvent<
    EmergencySafeUpdatedEvent.InputTuple,
    EmergencySafeUpdatedEvent.OutputTuple,
    EmergencySafeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "GracePeriodStarted"
  ): TypedContractEvent<
    GracePeriodStartedEvent.InputTuple,
    GracePeriodStartedEvent.OutputTuple,
    GracePeriodStartedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidationApproved"
  ): TypedContractEvent<
    LiquidationApprovedEvent.InputTuple,
    LiquidationApprovedEvent.OutputTuple,
    LiquidationApprovedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidationExecuted"
  ): TypedContractEvent<
    LiquidationExecutedEvent.InputTuple,
    LiquidationExecutedEvent.OutputTuple,
    LiquidationExecutedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidationReviewStarted"
  ): TypedContractEvent<
    LiquidationReviewStartedEvent.InputTuple,
    LiquidationReviewStartedEvent.OutputTuple,
    LiquidationReviewStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RepaymentRecorded"
  ): TypedContractEvent<
    RepaymentRecordedEvent.InputTuple,
    RepaymentRecordedEvent.OutputTuple,
    RepaymentRecordedEvent.OutputObject
  >;
  getEvent(
    key: "TreasurySafeUpdated"
  ): TypedContractEvent<
    TreasurySafeUpdatedEvent.InputTuple,
    TreasurySafeUpdatedEvent.OutputTuple,
    TreasurySafeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AgreementClosed(bytes32)": TypedContractEvent<
      AgreementClosedEvent.InputTuple,
      AgreementClosedEvent.OutputTuple,
      AgreementClosedEvent.OutputObject
    >;
    AgreementClosed: TypedContractEvent<
      AgreementClosedEvent.InputTuple,
      AgreementClosedEvent.OutputTuple,
      AgreementClosedEvent.OutputObject
    >;

    "AgreementCreated(bytes32,address,address,uint256,uint256,uint256)": TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;
    AgreementCreated: TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;

    "AgreementDefaulted(bytes32)": TypedContractEvent<
      AgreementDefaultedEvent.InputTuple,
      AgreementDefaultedEvent.OutputTuple,
      AgreementDefaultedEvent.OutputObject
    >;
    AgreementDefaulted: TypedContractEvent<
      AgreementDefaultedEvent.InputTuple,
      AgreementDefaultedEvent.OutputTuple,
      AgreementDefaultedEvent.OutputObject
    >;

    "AgreementFunded(bytes32,uint256)": TypedContractEvent<
      AgreementFundedEvent.InputTuple,
      AgreementFundedEvent.OutputTuple,
      AgreementFundedEvent.OutputObject
    >;
    AgreementFunded: TypedContractEvent<
      AgreementFundedEvent.InputTuple,
      AgreementFundedEvent.OutputTuple,
      AgreementFundedEvent.OutputObject
    >;

    "CollateralLocked(bytes32,uint256)": TypedContractEvent<
      CollateralLockedEvent.InputTuple,
      CollateralLockedEvent.OutputTuple,
      CollateralLockedEvent.OutputObject
    >;
    CollateralLocked: TypedContractEvent<
      CollateralLockedEvent.InputTuple,
      CollateralLockedEvent.OutputTuple,
      CollateralLockedEvent.OutputObject
    >;

    "CollateralReleased(bytes32,uint256)": TypedContractEvent<
      CollateralReleasedEvent.InputTuple,
      CollateralReleasedEvent.OutputTuple,
      CollateralReleasedEvent.OutputObject
    >;
    CollateralReleased: TypedContractEvent<
      CollateralReleasedEvent.InputTuple,
      CollateralReleasedEvent.OutputTuple,
      CollateralReleasedEvent.OutputObject
    >;

    "EmergencyPause(address)": TypedContractEvent<
      EmergencyPauseEvent.InputTuple,
      EmergencyPauseEvent.OutputTuple,
      EmergencyPauseEvent.OutputObject
    >;
    EmergencyPause: TypedContractEvent<
      EmergencyPauseEvent.InputTuple,
      EmergencyPauseEvent.OutputTuple,
      EmergencyPauseEvent.OutputObject
    >;

    "EmergencyResume(address)": TypedContractEvent<
      EmergencyResumeEvent.InputTuple,
      EmergencyResumeEvent.OutputTuple,
      EmergencyResumeEvent.OutputObject
    >;
    EmergencyResume: TypedContractEvent<
      EmergencyResumeEvent.InputTuple,
      EmergencyResumeEvent.OutputTuple,
      EmergencyResumeEvent.OutputObject
    >;

    "EmergencySafeUpdated(address,address)": TypedContractEvent<
      EmergencySafeUpdatedEvent.InputTuple,
      EmergencySafeUpdatedEvent.OutputTuple,
      EmergencySafeUpdatedEvent.OutputObject
    >;
    EmergencySafeUpdated: TypedContractEvent<
      EmergencySafeUpdatedEvent.InputTuple,
      EmergencySafeUpdatedEvent.OutputTuple,
      EmergencySafeUpdatedEvent.OutputObject
    >;

    "GracePeriodStarted(bytes32,uint256)": TypedContractEvent<
      GracePeriodStartedEvent.InputTuple,
      GracePeriodStartedEvent.OutputTuple,
      GracePeriodStartedEvent.OutputObject
    >;
    GracePeriodStarted: TypedContractEvent<
      GracePeriodStartedEvent.InputTuple,
      GracePeriodStartedEvent.OutputTuple,
      GracePeriodStartedEvent.OutputObject
    >;

    "LiquidationApproved(bytes32)": TypedContractEvent<
      LiquidationApprovedEvent.InputTuple,
      LiquidationApprovedEvent.OutputTuple,
      LiquidationApprovedEvent.OutputObject
    >;
    LiquidationApproved: TypedContractEvent<
      LiquidationApprovedEvent.InputTuple,
      LiquidationApprovedEvent.OutputTuple,
      LiquidationApprovedEvent.OutputObject
    >;

    "LiquidationExecuted(bytes32,uint256,uint256)": TypedContractEvent<
      LiquidationExecutedEvent.InputTuple,
      LiquidationExecutedEvent.OutputTuple,
      LiquidationExecutedEvent.OutputObject
    >;
    LiquidationExecuted: TypedContractEvent<
      LiquidationExecutedEvent.InputTuple,
      LiquidationExecutedEvent.OutputTuple,
      LiquidationExecutedEvent.OutputObject
    >;

    "LiquidationReviewStarted(bytes32)": TypedContractEvent<
      LiquidationReviewStartedEvent.InputTuple,
      LiquidationReviewStartedEvent.OutputTuple,
      LiquidationReviewStartedEvent.OutputObject
    >;
    LiquidationReviewStarted: TypedContractEvent<
      LiquidationReviewStartedEvent.InputTuple,
      LiquidationReviewStartedEvent.OutputTuple,
      LiquidationReviewStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RepaymentRecorded(bytes32,uint256)": TypedContractEvent<
      RepaymentRecordedEvent.InputTuple,
      RepaymentRecordedEvent.OutputTuple,
      RepaymentRecordedEvent.OutputObject
    >;
    RepaymentRecorded: TypedContractEvent<
      RepaymentRecordedEvent.InputTuple,
      RepaymentRecordedEvent.OutputTuple,
      RepaymentRecordedEvent.OutputObject
    >;

    "TreasurySafeUpdated(address,address)": TypedContractEvent<
      TreasurySafeUpdatedEvent.InputTuple,
      TreasurySafeUpdatedEvent.OutputTuple,
      TreasurySafeUpdatedEvent.OutputObject
    >;
    TreasurySafeUpdated: TypedContractEvent<
      TreasurySafeUpdatedEvent.InputTuple,
      TreasurySafeUpdatedEvent.OutputTuple,
      TreasurySafeUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
