/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PolicyControlledWalletInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedExecutor"
      | "domainSeparator"
      | "executeAuthorizedTransfer"
      | "nextNonce"
      | "owner"
      | "policySigner"
      | "renounceOwnership"
      | "setAuthorizedExecutor"
      | "setPolicySigner"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuthorizedExecutorUpdated"
      | "OwnershipTransferred"
      | "PolicySignerUpdated"
      | "WithdrawalExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedExecutor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "domainSeparator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeAuthorizedTransfer",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "nextNonce", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "policySigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPolicySigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "domainSeparator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeAuthorizedTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextNonce", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "policySigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPolicySigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AuthorizedExecutorUpdatedEvent {
  export type InputTuple = [
    previousAuthorizedExecutor: AddressLike,
    newAuthorizedExecutor: AddressLike
  ];
  export type OutputTuple = [
    previousAuthorizedExecutor: string,
    newAuthorizedExecutor: string
  ];
  export interface OutputObject {
    previousAuthorizedExecutor: string;
    newAuthorizedExecutor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicySignerUpdatedEvent {
  export type InputTuple = [
    previousPolicySigner: AddressLike,
    newPolicySigner: AddressLike
  ];
  export type OutputTuple = [
    previousPolicySigner: string,
    newPolicySigner: string
  ];
  export interface OutputObject {
    previousPolicySigner: string;
    newPolicySigner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalExecutedEvent {
  export type InputTuple = [
    intentId: BytesLike,
    asset: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    authorizationNonce: BigNumberish,
    executor: AddressLike
  ];
  export type OutputTuple = [
    intentId: string,
    asset: string,
    to: string,
    amount: bigint,
    authorizationNonce: bigint,
    executor: string
  ];
  export interface OutputObject {
    intentId: string;
    asset: string;
    to: string;
    amount: bigint;
    authorizationNonce: bigint;
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PolicyControlledWallet extends BaseContract {
  connect(runner?: ContractRunner | null): PolicyControlledWallet;
  waitForDeployment(): Promise<this>;

  interface: PolicyControlledWalletInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedExecutor: TypedContractMethod<[], [string], "view">;

  domainSeparator: TypedContractMethod<[], [string], "view">;

  executeAuthorizedTransfer: TypedContractMethod<
    [
      intentId: BytesLike,
      asset: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      authorizationNonce: BigNumberish,
      authorizationDeadline: BigNumberish,
      authorizationSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  nextNonce: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  policySigner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAuthorizedExecutor: TypedContractMethod<
    [newAuthorizedExecutor: AddressLike],
    [void],
    "nonpayable"
  >;

  setPolicySigner: TypedContractMethod<
    [newPolicySigner: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedExecutor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "domainSeparator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "executeAuthorizedTransfer"
  ): TypedContractMethod<
    [
      intentId: BytesLike,
      asset: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      authorizationNonce: BigNumberish,
      authorizationDeadline: BigNumberish,
      authorizationSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextNonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policySigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAuthorizedExecutor"
  ): TypedContractMethod<
    [newAuthorizedExecutor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPolicySigner"
  ): TypedContractMethod<[newPolicySigner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AuthorizedExecutorUpdated"
  ): TypedContractEvent<
    AuthorizedExecutorUpdatedEvent.InputTuple,
    AuthorizedExecutorUpdatedEvent.OutputTuple,
    AuthorizedExecutorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PolicySignerUpdated"
  ): TypedContractEvent<
    PolicySignerUpdatedEvent.InputTuple,
    PolicySignerUpdatedEvent.OutputTuple,
    PolicySignerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalExecuted"
  ): TypedContractEvent<
    WithdrawalExecutedEvent.InputTuple,
    WithdrawalExecutedEvent.OutputTuple,
    WithdrawalExecutedEvent.OutputObject
  >;

  filters: {
    "AuthorizedExecutorUpdated(address,address)": TypedContractEvent<
      AuthorizedExecutorUpdatedEvent.InputTuple,
      AuthorizedExecutorUpdatedEvent.OutputTuple,
      AuthorizedExecutorUpdatedEvent.OutputObject
    >;
    AuthorizedExecutorUpdated: TypedContractEvent<
      AuthorizedExecutorUpdatedEvent.InputTuple,
      AuthorizedExecutorUpdatedEvent.OutputTuple,
      AuthorizedExecutorUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PolicySignerUpdated(address,address)": TypedContractEvent<
      PolicySignerUpdatedEvent.InputTuple,
      PolicySignerUpdatedEvent.OutputTuple,
      PolicySignerUpdatedEvent.OutputObject
    >;
    PolicySignerUpdated: TypedContractEvent<
      PolicySignerUpdatedEvent.InputTuple,
      PolicySignerUpdatedEvent.OutputTuple,
      PolicySignerUpdatedEvent.OutputObject
    >;

    "WithdrawalExecuted(bytes32,address,address,uint256,uint256,address)": TypedContractEvent<
      WithdrawalExecutedEvent.InputTuple,
      WithdrawalExecutedEvent.OutputTuple,
      WithdrawalExecutedEvent.OutputObject
    >;
    WithdrawalExecuted: TypedContractEvent<
      WithdrawalExecutedEvent.InputTuple,
      WithdrawalExecutedEvent.OutputTuple,
      WithdrawalExecutedEvent.OutputObject
    >;
  };
}
