/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SolvencyReportAnchorRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anchorSolvencyReport"
      | "authorizedAnchorer"
      | "getAnchorRecord"
      | "isAnchored"
      | "owner"
      | "renounceOwnership"
      | "setAuthorizedAnchorer"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuthorizedAnchorerUpdated"
      | "OwnershipTransferred"
      | "SolvencyReportAnchored"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "anchorSolvencyReport",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedAnchorer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAnchorRecord",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAnchored",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedAnchorer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "anchorSolvencyReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedAnchorer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAnchorRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAnchored", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedAnchorer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AuthorizedAnchorerUpdatedEvent {
  export type InputTuple = [
    previousAuthorizedAnchorer: AddressLike,
    nextAuthorizedAnchorer: AddressLike
  ];
  export type OutputTuple = [
    previousAuthorizedAnchorer: string,
    nextAuthorizedAnchorer: string
  ];
  export interface OutputObject {
    previousAuthorizedAnchorer: string;
    nextAuthorizedAnchorer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SolvencyReportAnchoredEvent {
  export type InputTuple = [
    anchorPayloadHash: BytesLike,
    reportIdHash: BytesLike,
    snapshotIdHash: BytesLike,
    reportChainId: BigNumberish,
    anchorer: AddressLike,
    anchoredAt: BigNumberish
  ];
  export type OutputTuple = [
    anchorPayloadHash: string,
    reportIdHash: string,
    snapshotIdHash: string,
    reportChainId: bigint,
    anchorer: string,
    anchoredAt: bigint
  ];
  export interface OutputObject {
    anchorPayloadHash: string;
    reportIdHash: string;
    snapshotIdHash: string;
    reportChainId: bigint;
    anchorer: string;
    anchoredAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SolvencyReportAnchorRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SolvencyReportAnchorRegistry;
  waitForDeployment(): Promise<this>;

  interface: SolvencyReportAnchorRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchorSolvencyReport: TypedContractMethod<
    [
      anchorPayloadHash: BytesLike,
      reportIdHash: BytesLike,
      snapshotIdHash: BytesLike,
      reportChainId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  authorizedAnchorer: TypedContractMethod<[], [string], "view">;

  getAnchorRecord: TypedContractMethod<
    [anchorPayloadHash: BytesLike],
    [
      [string, string, bigint, bigint, string] & {
        reportIdHash: string;
        snapshotIdHash: string;
        reportChainId: bigint;
        anchoredAt: bigint;
        anchorer: string;
      }
    ],
    "view"
  >;

  isAnchored: TypedContractMethod<
    [anchorPayloadHash: BytesLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAuthorizedAnchorer: TypedContractMethod<
    [nextAuthorizedAnchorer: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchorSolvencyReport"
  ): TypedContractMethod<
    [
      anchorPayloadHash: BytesLike,
      reportIdHash: BytesLike,
      snapshotIdHash: BytesLike,
      reportChainId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedAnchorer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAnchorRecord"
  ): TypedContractMethod<
    [anchorPayloadHash: BytesLike],
    [
      [string, string, bigint, bigint, string] & {
        reportIdHash: string;
        snapshotIdHash: string;
        reportChainId: bigint;
        anchoredAt: bigint;
        anchorer: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAnchored"
  ): TypedContractMethod<[anchorPayloadHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAuthorizedAnchorer"
  ): TypedContractMethod<
    [nextAuthorizedAnchorer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AuthorizedAnchorerUpdated"
  ): TypedContractEvent<
    AuthorizedAnchorerUpdatedEvent.InputTuple,
    AuthorizedAnchorerUpdatedEvent.OutputTuple,
    AuthorizedAnchorerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SolvencyReportAnchored"
  ): TypedContractEvent<
    SolvencyReportAnchoredEvent.InputTuple,
    SolvencyReportAnchoredEvent.OutputTuple,
    SolvencyReportAnchoredEvent.OutputObject
  >;

  filters: {
    "AuthorizedAnchorerUpdated(address,address)": TypedContractEvent<
      AuthorizedAnchorerUpdatedEvent.InputTuple,
      AuthorizedAnchorerUpdatedEvent.OutputTuple,
      AuthorizedAnchorerUpdatedEvent.OutputObject
    >;
    AuthorizedAnchorerUpdated: TypedContractEvent<
      AuthorizedAnchorerUpdatedEvent.InputTuple,
      AuthorizedAnchorerUpdatedEvent.OutputTuple,
      AuthorizedAnchorerUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SolvencyReportAnchored(bytes32,bytes32,bytes32,uint256,address,uint256)": TypedContractEvent<
      SolvencyReportAnchoredEvent.InputTuple,
      SolvencyReportAnchoredEvent.OutputTuple,
      SolvencyReportAnchoredEvent.OutputObject
    >;
    SolvencyReportAnchored: TypedContractEvent<
      SolvencyReportAnchoredEvent.InputTuple,
      SolvencyReportAnchoredEvent.OutputTuple,
      SolvencyReportAnchoredEvent.OutputObject
    >;
  };
}
