/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface StakingV1Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "bindPositionBeneficiary"
      | "claimReward"
      | "emergencySafe"
      | "fundRewards"
      | "getPosition"
      | "owner"
      | "pause"
      | "paused"
      | "recordDeposit"
      | "recordRewardAccrual"
      | "recordWithdrawal"
      | "renounceOwnership"
      | "rewardReserve"
      | "setEmergencySafe"
      | "setTreasurySafe"
      | "totalStaked"
      | "transferOwnership"
      | "treasurySafe"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyPause"
      | "EmergencyResume"
      | "EmergencySafeUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "PositionBeneficiaryBound"
      | "PositionDeposited"
      | "PositionWithdrawn"
      | "RewardAccrued"
      | "RewardClaimed"
      | "RewardsFunded"
      | "TreasurySafeUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "bindPositionBeneficiary",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencySafe",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordDeposit",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordRewardAccrual",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordWithdrawal",
    values: [BytesLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardReserve",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setEmergencySafe",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasurySafe",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalStaked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "treasurySafe",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "bindPositionBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencySafe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordRewardAccrual",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEmergencySafe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasurySafe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasurySafe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace EmergencyPauseEvent {
  export type InputTuple = [triggeredBy: AddressLike];
  export type OutputTuple = [triggeredBy: string];
  export interface OutputObject {
    triggeredBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyResumeEvent {
  export type InputTuple = [triggeredBy: AddressLike];
  export type OutputTuple = [triggeredBy: string];
  export interface OutputObject {
    triggeredBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencySafeUpdatedEvent {
  export type InputTuple = [
    previousEmergencySafe: AddressLike,
    nextEmergencySafe: AddressLike
  ];
  export type OutputTuple = [
    previousEmergencySafe: string,
    nextEmergencySafe: string
  ];
  export interface OutputObject {
    previousEmergencySafe: string;
    nextEmergencySafe: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionBeneficiaryBoundEvent {
  export type InputTuple = [positionId: BytesLike, beneficiary: AddressLike];
  export type OutputTuple = [positionId: string, beneficiary: string];
  export interface OutputObject {
    positionId: string;
    beneficiary: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionDepositedEvent {
  export type InputTuple = [
    positionId: BytesLike,
    beneficiary: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    positionId: string,
    beneficiary: string,
    amount: bigint
  ];
  export interface OutputObject {
    positionId: string;
    beneficiary: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionWithdrawnEvent {
  export type InputTuple = [
    positionId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    positionId: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    positionId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardAccruedEvent {
  export type InputTuple = [positionId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [positionId: string, amount: bigint];
  export interface OutputObject {
    positionId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [
    positionId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    positionId: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    positionId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsFundedEvent {
  export type InputTuple = [treasurySafe: AddressLike, amount: BigNumberish];
  export type OutputTuple = [treasurySafe: string, amount: bigint];
  export interface OutputObject {
    treasurySafe: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasurySafeUpdatedEvent {
  export type InputTuple = [
    previousTreasurySafe: AddressLike,
    nextTreasurySafe: AddressLike
  ];
  export type OutputTuple = [
    previousTreasurySafe: string,
    nextTreasurySafe: string
  ];
  export interface OutputObject {
    previousTreasurySafe: string;
    nextTreasurySafe: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StakingV1 extends BaseContract {
  connect(runner?: ContractRunner | null): StakingV1;
  waitForDeployment(): Promise<this>;

  interface: StakingV1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bindPositionBeneficiary: TypedContractMethod<
    [positionId: BytesLike, beneficiary: AddressLike],
    [void],
    "nonpayable"
  >;

  claimReward: TypedContractMethod<
    [positionId: BytesLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  emergencySafe: TypedContractMethod<[], [string], "view">;

  fundRewards: TypedContractMethod<[], [void], "payable">;

  getPosition: TypedContractMethod<
    [positionId: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        beneficiary: string;
        stakedAmount: bigint;
        accruedRewardAmount: bigint;
        claimedRewardAmount: bigint;
        initialized: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  recordDeposit: TypedContractMethod<
    [positionId: BytesLike, beneficiary: AddressLike],
    [void],
    "payable"
  >;

  recordRewardAccrual: TypedContractMethod<
    [positionId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordWithdrawal: TypedContractMethod<
    [positionId: BytesLike, amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rewardReserve: TypedContractMethod<[], [bigint], "view">;

  setEmergencySafe: TypedContractMethod<
    [nextEmergencySafe: AddressLike],
    [void],
    "nonpayable"
  >;

  setTreasurySafe: TypedContractMethod<
    [nextTreasurySafe: AddressLike],
    [void],
    "nonpayable"
  >;

  totalStaked: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasurySafe: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bindPositionBeneficiary"
  ): TypedContractMethod<
    [positionId: BytesLike, beneficiary: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<
    [positionId: BytesLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencySafe"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fundRewards"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getPosition"
  ): TypedContractMethod<
    [positionId: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        beneficiary: string;
        stakedAmount: bigint;
        accruedRewardAmount: bigint;
        claimedRewardAmount: bigint;
        initialized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "recordDeposit"
  ): TypedContractMethod<
    [positionId: BytesLike, beneficiary: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "recordRewardAccrual"
  ): TypedContractMethod<
    [positionId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordWithdrawal"
  ): TypedContractMethod<
    [positionId: BytesLike, amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardReserve"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setEmergencySafe"
  ): TypedContractMethod<
    [nextEmergencySafe: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasurySafe"
  ): TypedContractMethod<[nextTreasurySafe: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalStaked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasurySafe"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "EmergencyPause"
  ): TypedContractEvent<
    EmergencyPauseEvent.InputTuple,
    EmergencyPauseEvent.OutputTuple,
    EmergencyPauseEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyResume"
  ): TypedContractEvent<
    EmergencyResumeEvent.InputTuple,
    EmergencyResumeEvent.OutputTuple,
    EmergencyResumeEvent.OutputObject
  >;
  getEvent(
    key: "EmergencySafeUpdated"
  ): TypedContractEvent<
    EmergencySafeUpdatedEvent.InputTuple,
    EmergencySafeUpdatedEvent.OutputTuple,
    EmergencySafeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PositionBeneficiaryBound"
  ): TypedContractEvent<
    PositionBeneficiaryBoundEvent.InputTuple,
    PositionBeneficiaryBoundEvent.OutputTuple,
    PositionBeneficiaryBoundEvent.OutputObject
  >;
  getEvent(
    key: "PositionDeposited"
  ): TypedContractEvent<
    PositionDepositedEvent.InputTuple,
    PositionDepositedEvent.OutputTuple,
    PositionDepositedEvent.OutputObject
  >;
  getEvent(
    key: "PositionWithdrawn"
  ): TypedContractEvent<
    PositionWithdrawnEvent.InputTuple,
    PositionWithdrawnEvent.OutputTuple,
    PositionWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "RewardAccrued"
  ): TypedContractEvent<
    RewardAccruedEvent.InputTuple,
    RewardAccruedEvent.OutputTuple,
    RewardAccruedEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsFunded"
  ): TypedContractEvent<
    RewardsFundedEvent.InputTuple,
    RewardsFundedEvent.OutputTuple,
    RewardsFundedEvent.OutputObject
  >;
  getEvent(
    key: "TreasurySafeUpdated"
  ): TypedContractEvent<
    TreasurySafeUpdatedEvent.InputTuple,
    TreasurySafeUpdatedEvent.OutputTuple,
    TreasurySafeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "EmergencyPause(address)": TypedContractEvent<
      EmergencyPauseEvent.InputTuple,
      EmergencyPauseEvent.OutputTuple,
      EmergencyPauseEvent.OutputObject
    >;
    EmergencyPause: TypedContractEvent<
      EmergencyPauseEvent.InputTuple,
      EmergencyPauseEvent.OutputTuple,
      EmergencyPauseEvent.OutputObject
    >;

    "EmergencyResume(address)": TypedContractEvent<
      EmergencyResumeEvent.InputTuple,
      EmergencyResumeEvent.OutputTuple,
      EmergencyResumeEvent.OutputObject
    >;
    EmergencyResume: TypedContractEvent<
      EmergencyResumeEvent.InputTuple,
      EmergencyResumeEvent.OutputTuple,
      EmergencyResumeEvent.OutputObject
    >;

    "EmergencySafeUpdated(address,address)": TypedContractEvent<
      EmergencySafeUpdatedEvent.InputTuple,
      EmergencySafeUpdatedEvent.OutputTuple,
      EmergencySafeUpdatedEvent.OutputObject
    >;
    EmergencySafeUpdated: TypedContractEvent<
      EmergencySafeUpdatedEvent.InputTuple,
      EmergencySafeUpdatedEvent.OutputTuple,
      EmergencySafeUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PositionBeneficiaryBound(bytes32,address)": TypedContractEvent<
      PositionBeneficiaryBoundEvent.InputTuple,
      PositionBeneficiaryBoundEvent.OutputTuple,
      PositionBeneficiaryBoundEvent.OutputObject
    >;
    PositionBeneficiaryBound: TypedContractEvent<
      PositionBeneficiaryBoundEvent.InputTuple,
      PositionBeneficiaryBoundEvent.OutputTuple,
      PositionBeneficiaryBoundEvent.OutputObject
    >;

    "PositionDeposited(bytes32,address,uint256)": TypedContractEvent<
      PositionDepositedEvent.InputTuple,
      PositionDepositedEvent.OutputTuple,
      PositionDepositedEvent.OutputObject
    >;
    PositionDeposited: TypedContractEvent<
      PositionDepositedEvent.InputTuple,
      PositionDepositedEvent.OutputTuple,
      PositionDepositedEvent.OutputObject
    >;

    "PositionWithdrawn(bytes32,address,uint256)": TypedContractEvent<
      PositionWithdrawnEvent.InputTuple,
      PositionWithdrawnEvent.OutputTuple,
      PositionWithdrawnEvent.OutputObject
    >;
    PositionWithdrawn: TypedContractEvent<
      PositionWithdrawnEvent.InputTuple,
      PositionWithdrawnEvent.OutputTuple,
      PositionWithdrawnEvent.OutputObject
    >;

    "RewardAccrued(bytes32,uint256)": TypedContractEvent<
      RewardAccruedEvent.InputTuple,
      RewardAccruedEvent.OutputTuple,
      RewardAccruedEvent.OutputObject
    >;
    RewardAccrued: TypedContractEvent<
      RewardAccruedEvent.InputTuple,
      RewardAccruedEvent.OutputTuple,
      RewardAccruedEvent.OutputObject
    >;

    "RewardClaimed(bytes32,address,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "RewardsFunded(address,uint256)": TypedContractEvent<
      RewardsFundedEvent.InputTuple,
      RewardsFundedEvent.OutputTuple,
      RewardsFundedEvent.OutputObject
    >;
    RewardsFunded: TypedContractEvent<
      RewardsFundedEvent.InputTuple,
      RewardsFundedEvent.OutputTuple,
      RewardsFundedEvent.OutputObject
    >;

    "TreasurySafeUpdated(address,address)": TypedContractEvent<
      TreasurySafeUpdatedEvent.InputTuple,
      TreasurySafeUpdatedEvent.OutputTuple,
      TreasurySafeUpdatedEvent.OutputObject
    >;
    TreasurySafeUpdated: TypedContractEvent<
      TreasurySafeUpdatedEvent.InputTuple,
      TreasurySafeUpdatedEvent.OutputTuple,
      TreasurySafeUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
