export const RELEASE_READINESS_IDENTIFIER_MAX_LENGTH = 200;
export const RELEASE_READINESS_SUMMARY_MAX_LENGTH = 1_000;
export const RELEASE_READINESS_NOTE_MAX_LENGTH = 4_000;
export const RELEASE_READINESS_RUNBOOK_PATH_MAX_LENGTH = 200;
export const RELEASE_READINESS_EVIDENCE_LINK_MAX_LENGTH = 500;
export const RELEASE_READINESS_OPEN_BLOCKER_MAX_LENGTH = 500;
export const RELEASE_READINESS_LIST_LIMIT_MAX = 100;
export const RELEASE_READINESS_SINCE_DAYS_MAX = 365;
