export const OPERATOR_CASE_NOTE_MAX_LENGTH = 2_000;
export const OPERATOR_CASE_REASON_CODE_MAX_LENGTH = 100;
export const OPERATOR_CASE_FILTER_VALUE_MAX_LENGTH = 200;
export const OPERATOR_CASE_EMAIL_MAX_LENGTH = 320;
export const OPERATOR_CASE_REASON_CODE_PATTERN = /^[a-z0-9_]+$/;
export const OPERATOR_CASE_NOTE_CONTENT_PATTERN = /\S/;
